name: Build and Test PR

on:
  pull_request: # Trigger for pull requests.
    types: [opened, synchronize, reopened]
    branches:
      - main
      - v[0-9]*
  workflow_dispatch: # Allows for manual triggering.
    inputs:
      ref:
        description: "The ref to build and test."
        required: false

# If another instance of this workflow is started for the same PR, cancel the
# old one.  If a PR is updated and a new test run is started, the old test run
# will be cancelled automatically to conserve resources.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        os: ["macos-latest"]
        browser: ["Safari"]
      # Disable fail-fast so that one matrix-job failing doesn't make the other
      # ones end early.
      fail-fast: false

    name: ${{ matrix.os }} ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}

    steps:
      # Firefox on Ubuntu appears to not have the right things installed in
      # the environment used by GitHub actions, so make sure that ffmpeg is
      # installed. Otherwise, the browser might not support some codecs that the
      # tests assume will be supported.
      - name: Install FFmpeg
        if: matrix.os == 'ubuntu-latest' && matrix.browser == 'Firefox'
        run: sudo apt -y update && sudo apt -y install ffmpeg

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      # Safari 14 can be installed, but not to the root, and it can't replace
      # the standard version, at least not on GitHub's VMs.  If you try to
      # install directly to the root with sudo, it will appear to succeed, but
      # will have no effect.  If you try to script it explicitly with rm -rf
      # and cp, this will fail.  Safari may be on a read-only filesystem.
      - name: Install Safari 14 to home directory
        if: matrix.os == 'macos-latest' && matrix.browser == 'Safari-14'
        run: |
          # Download Safari 14
          # See also https://www.macupdate.com/app/mac/15675/apple-safari/old-versions
          curl -Lv https://www.macupdate.com/action/download/63550 > safari-14.1.2.pkg

          # Install Safari 14 to homedir specifically.
          installer -pkg safari-14.1.2.pkg -target CurrentUserHomeDirectory

          # Install a launcher that can execute a shell script to launch this
          npm install karma-script-launcher --save-dev

      - name: Build Player
        run: python build/all.py

      - name: Test Player
        shell: bash
        run: |
          browser=${{ matrix.browser }}

          if [[ "$browser" == "Safari-14" ]]; then
            # Replace the browser name with a script that can launch this
            # browser from the command line.
            browser="$PWD/.github/workflows/safari-homedir-launcher.sh"
          fi

          # Install deps, freeze them, and patch karma for debugging Safari.
          npm ci
          touch node_modules/.last_update
          patch -p0 -i .github/workflows/debug-karma.patch

          python build/test.py \
            --browsers "$browser" \
            --reporters spec --spec-hide-passed \
            --drm \
            ${{ matrix.extra_flags }}
