name: Build and Test PR

on:
  pull_request: # Trigger for pull requests.
    types: [opened, synchronize, reopened]
    branches:
      - main
      - v[0-9]*
  workflow_dispatch: # Allows for manual triggering.
    inputs:
      ref:
        description: "The ref to build and test."
        required: false

# If another instance of this workflow is started for the same PR, cancel the
# old one.  If a PR is updated and a new test run is started, the old test run
# will be cancelled automatically to conserve resources.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Lint
        run: python build/check.py

  build_and_test:
    # Don't waste time doing a full matrix of test runs when there was an
    # obvious linter error.
    needs: lint
    strategy:
      matrix:
        include:
          # Run Linux browsers with xvfb, so they're in a headless X session.
          # Additionally, generate a code coverage report from Linux Chrome.
          - os: ubuntu-latest
            browser: Chrome
            extra_flags: "--use-xvfb --html-coverage-report"
          - os: ubuntu-latest
            browser: Firefox
            extra_flags: "--use-xvfb"

          - os: macos-latest
            browser: Chrome
          - os: macos-latest
            browser: Firefox
          - os: macos-latest
            browser: Edge
          - os: macos-latest
            browser: Safari
          - os: macos-latest
            browser: Safari-14

          - os: windows-latest
            browser: Chrome
          - os: windows-latest
            browser: Firefox
          - os: windows-latest
            browser: Edge

      # Disable fail-fast so that one matrix-job failing doesn't make the other
      # ones end early.
      fail-fast: false

    name: ${{ matrix.os }} ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}

    steps:
      # Firefox on Ubuntu appears to not have the right things installed in
      # the environment used by GitHub actions, so make sure that ffmpeg is
      # installed. Otherwise, the browser might not support some codecs that the
      # tests assume will be supported.
      - name: Install FFmpeg
        if: matrix.os == 'ubuntu-latest' && matrix.browser == 'Firefox'
        run: sudo apt -y update && sudo apt -y install ffmpeg

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      # Safari 14 can be installed, but not to the root, and it can't replace
      # the standard version, at least not on GitHub's VMs.  If you try to
      # install directly to the root with sudo, it will appear to succeed, but
      # will have no effect.  If you try to script it explicitly with rm -rf
      # and cp, this will fail.  Safari may be on a read-only filesystem.
      - name: Install Safari 14 to home directory
        if: matrix.os == 'macos-latest' && matrix.browser == 'Safari-14'
        run: |
          # Download Safari 14
          # See also https://www.macupdate.com/app/mac/15675/apple-safari/old-versions
          curl -Lv https://www.macupdate.com/action/download/62946 > Safari14.0CatalinaAuto.pkg.zip

          # Install Safari 14 to homedir specifically.
          unzip Safari14.0CatalinaAuto.pkg.zip
          installer -pkg Safari14.0CatalinaAuto.pkg -target CurrentUserHomeDirectory

          # Install a launcher that can execute a shell script to launch this
          npm install karma-script-launcher --save-dev

      - name: Build Player
        run: python build/all.py

      - name: Test Player
        shell: bash
        run: |
          browser=${{ matrix.browser }}

          if [[ "$browser" == "Safari-14" ]]; then
            # Replace the browser name with a script that can launch this
            # browser from the command line.
            browser="$PWD/.github/workflows/safari-homedir-launcher.sh"
          fi

          python build/test.py \
            --browsers "$browser" \
            --reporters spec --spec-hide-passed \
            ${{ matrix.extra_flags }}

      - name: Find coverage report
        id: coverage
        if: always() # Even on failure of an earlier step.
        shell: bash
        run: |
          # If the directory exists...
          if [ -d coverage ]; then
            # Find the path to the coverage report.  It includes the exact
            # browser version in the path, so it will vary.  Having a single
            # path will make the artifact zip simpler, whereas using a wildcard
            # in the upload step will result in a zip file with internal
            # directories.  In case there are multiple folders (there shouldn't
            # be), this shell script will extract just a single path.
            coverage_report="$( (ls coverage/*/coverage.json || true) | head -1 )"

            # Show what's there, for debugging purposes.
            ls -l coverage/

            if [ -f "$coverage_report" ]; then
              echo "Found coverage report: $coverage_report"
              echo "::set-output name=coverage_report::$coverage_report"
            else
              echo "Could not locate coverage report!"
              exit 1
            fi
          else
            echo "No coverage report generated."
          fi

      - uses: actions/upload-artifact@v3
        # If there's a coverage report, upload it, even if a previous step
        # failed.
        if: ${{ always() && steps.coverage.outputs.coverage_report }}
        with:
          # This will create a download called coverage.zip containing only
          # coverage.json.
          path: ${{ steps.coverage.outputs.coverage_report }}
          name: coverage
          # Since we've already filtered this step for instances where there is
          # an environment variable set for this, the file should definitely be
          # there.
          if-no-files-found: error

  build_in_docker:
    # Don't waste time doing a full matrix of test runs when there was an
    # obvious linter error.
    needs: lint
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Docker
        run: docker-compose -f build/docker/docker-compose.yml up
